import type { Achievement } from '../types';

export const ACHIEVEMENTS: Achievement[] = [
  // CATEGORY 1 — GOAL COMPLETION
  {
    id: 'first-step',
    name: 'First Step',
    description: 'Complete your first goal.',
    category: 'goal',
    icon: 'Footprints',
    requirement: { type: 'total_completed', value: 1 },
    xpReward: 25,
  },
  {
    id: 'goal-getter',
    name: 'Goal Getter',
    description: 'Complete 10 goals.',
    category: 'goal',
    icon: 'Target',
    requirement: { type: 'total_completed', value: 10 },
    xpReward: 100,
  },
  {
    id: 'goal-machine',
    name: 'Goal Machine',
    description: 'Complete 50 goals.',
    category: 'goal',
    icon: 'Zap',
    requirement: { type: 'total_completed', value: 50 },
    xpReward: 250,
  },
  {
    id: 'goal-master',
    name: 'Goal Master',
    description: 'Complete 100 goals.',
    category: 'goal',
    icon: 'Trophy',
    requirement: { type: 'total_completed', value: 100 },
    xpReward: 500,
  },

  // CATEGORY 2 — STREAKS
  {
    id: 'streak-3',
    name: '3-Day Streak',
    description: 'Complete goals for 3 consecutive days.',
    category: 'streak',
    icon: 'Flame',
    requirement: { type: 'streak', value: 3 },
    xpReward: 30,
  },
  {
    id: 'streak-7',
    name: '7-Day Streak',
    description: 'Complete goals for 7 consecutive days.',
    category: 'streak',
    icon: 'Flame',
    requirement: { type: 'streak', value: 7 },
    xpReward: 70,
  },
  {
    id: 'streak-14',
    name: '14-Day Streak',
    description: 'Complete goals for 14 consecutive days.',
    category: 'streak',
    icon: 'Flame',
    requirement: { type: 'streak', value: 14 },
    xpReward: 150,
  },
  {
    id: 'streak-30',
    name: '30-Day Streak',
    description: 'Complete goals for 30 consecutive days.',
    category: 'streak',
    icon: 'Flame',
    requirement: { type: 'streak', value: 30 },
    xpReward: 300,
  },
  {
    id: 'streak-100',
    name: '100-Day Streak',
    description: 'Complete goals for 100 consecutive days.',
    category: 'streak',
    icon: 'Flame',
    requirement: { type: 'streak', value: 100 },
    xpReward: 1000,
  },

  // CATEGORY 3 — WEEKLY TARGETS
  {
    id: 'perfect-week',
    name: 'Perfect Week',
    description: 'Complete 100% of planned goals for one week.',
    category: 'weekly',
    icon: 'Trophy',
    requirement: { type: 'perfect_weeks', value: 1 },
    xpReward: 100,
  },
  {
    id: 'strong-week',
    name: 'Strong Week',
    description: 'Complete at least 80% of planned goals.',
    category: 'weekly',
    icon: 'Zap',
    requirement: { type: 'strong_weeks', value: 1 },
    xpReward: 80,
  },
  {
    id: 'consistent',
    name: 'Consistent',
    description: 'Complete at least 70% for 4 consecutive weeks.',
    category: 'weekly',
    icon: 'Target',
    requirement: { type: 'consistent_weeks', value: 4 },
    xpReward: 200,
  },

  // CATEGORY 4 — MILESTONES
  {
    id: 'first-week',
    name: 'First Week',
    description: 'Complete your first week.',
    category: 'milestone',
    icon: 'Calendar',
    requirement: { type: 'active_days', value: 7 },
    xpReward: 50,
  },
  {
    id: 'first-month',
    name: 'First Month',
    description: 'Track your goals for 30 days.',
    category: 'milestone',
    icon: 'CalendarDays',
    requirement: { type: 'active_days', value: 30 },
    xpReward: 150,
  },
  {
    id: 'habit-builder',
    name: 'Habit Builder',
    description: 'Maintain at least 3 active goals for 30 days.',
    category: 'milestone',
    icon: 'Sparkles',
    requirement: { type: 'active_goals_30_days', value: 3 },
    xpReward: 200,
  },

  // CATEGORY 5 — SPECIAL
  {
    id: 'early-bird',
    name: 'Early Bird',
    description: 'Complete a morning goal 7 times.',
    category: 'special',
    icon: 'Sun',
    requirement: { type: 'morning_goals', value: 7 },
    xpReward: 75,
  },
  {
    id: 'healthy-choice',
    name: 'Healthy Choice',
    description: 'Complete "Eat & drink healthy" 10 times.',
    category: 'special',
    icon: 'Apple',
    requirement: { type: 'specific_goal', title: 'Eat & drink healthy', value: 10 },
    xpReward: 100,
  },
  {
    id: 'hydration-hero',
    name: 'Hydration Hero',
    description: 'Complete water goals 10 times.',
    category: 'special',
    icon: 'Droplets',
    requirement: { type: 'specific_goal_category', category: 'water', value: 10 },
    xpReward: 100,
  },
  {
    id: 'bookworm',
    name: 'Bookworm',
    description: 'Complete reading goals 10 times.',
    category: 'special',
    icon: 'BookOpen',
    requirement: { type: 'specific_goal_category', category: 'reading', value: 10 },
    xpReward: 100,
  },
];
